<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <EnableUnsafeBinaryFormatterSerialization>true</EnableUnsafeBinaryFormatterSerialization>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="LibraryWindow.xaml" />
    <None Remove="Pages\EndpointEditor.xaml" />
    <None Remove="Pages\MappingEditor.xaml" />
    <None Remove="Pages\ProjectOverview.xaml" />
    <None Remove="Pages\ProjectOverviewControls\OverviewRibbon.xaml" />
    <None Remove="Pages\ProjectOverviewControls\ProjectCanvas.xaml" />
    <None Remove="Pages\ProjectOverviewControls\ProjectEndpoint.xaml" />
    <None Remove="Pages\ProjectOverviewControls\ProjectMapping.xaml" />
  </ItemGroup>
  
  <ItemGroup>
    <PackageReference Include="Autofac" Version="4.9.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Transmogrify.Data\Transmogrify.Data.csproj" />
    <ProjectReference Include="..\Transmogrify.Engine\Transmogrify.Engine.csproj" />
    <ProjectReference Include="..\Transmogrify.Operations\Transmogrify.Operations.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="LibraryWindow.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Pages\EndpointEditor.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Pages\MappingEditor.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Pages\ProjectOverviewControls\OverviewRibbon.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Pages\ProjectOverviewControls\ProjectEndpoint.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Pages\ProjectOverviewControls\ProjectCanvas.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Pages\ProjectOverviewControls\ProjectMapping.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <Page Update="LibraryWindow.xaml">
      <SubType>Designer</SubType>
    </Page>
    <Page Update="Pages\EndpointEditor.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Update="Pages\MappingEditor.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Update="Pages\ProjectOverviewControls\OverviewRibbon.xaml">
      <SubType>Designer</SubType>
    </Page>
    <Page Update="Pages\ProjectOverviewControls\ProjectEndpoint.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Update="Pages\ProjectOverviewControls\ProjectCanvas.xaml">
      <SubType>Designer</SubType>
    </Page>
    <Page Update="Pages\ProjectOverviewControls\ProjectMapping.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Update="Pages\ProjectOverview.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>

</Project>